#!/usr/bin/env python3
import os
import json
from discovery import fetch_github_metrics

def generate_vessel_reports():
    vessels = fetch_github_metrics("popdeuxrem")
    output_dir = "docs/deployments"
    os.makedirs(output_dir, exist_ok=True)

    report_index = []

    for vessel in vessels:
        name = vessel['name']
        filename = f"{name}.md"
        path = os.path.join(output_dir, filename)
        
        report_content = f"""# 🚢 Vessel Report: {name}
## ◈ METRICS
- **Stars**: {vessel.get('stargazers_count', 0)}
- **Forks**: {vessel.get('forks_count', 0)}
- **Issues**: {vessel.get('open_issues_count', 0)}
- **Language**: {vessel.get('language', 'Unknown')}

## ◈ DESCRIPTION
{vessel.get('description', 'No description provided.')}

## ◈ UPLINK
[View Repository]({vessel.get('html_url')})

---
*Generated by QuantumProfileSurface/v4.1 VesselEngine*
"""
        with open(path, 'w') as f:
            f.write(report_content)
        
        report_index.append(f"- [{name}](./{filename})")

    # Create an index file
    with open(os.path.join(output_dir, "INDEX.md"), 'w') as f:
        f.write("# 📂 Deployment Index\n\n" + "\n".join(report_index))
    
    print(f"◈ {len(vessels)} Vessel Reports generated in {output_dir}")

if __name__ == "__main__":
    generate_vessel_reports()
