import json
import os
from pathlib import Path

def generate_readme():
    print(">> Assembling Quantum Surface...")
    
    # Load Data
    try:
        with open('portfolio.json', 'r') as f:
            projects = json.load(f)
    except FileNotFoundError:
        projects = []

    # 1. Header & Console
    header = """<!-- PROFILE_README_SPEC: QuantumProfileSurface/v3.0 -->
<!-- GENERATED BY: scripts/update_readme.py -->

<div align="center">
  <img src="assets/header-plate.svg" alt="Quantum Identity Header" width="100%" />
  <br /><br />
  <h1>𖢧ꛅ · 🜂 LYSERGIC · 𖢧ꛕ</h1>
  <p>
    <strong>Systems Architect · Automation Operator</strong><br/>
    <sub>Auditable Pipelines · Reversible State · Security-First Ops</sub>
  </p>
</div>

---

<p align="center">
  <img src="assets/bg-quantum-grid.svg" width="100%" alt="divider" />
</p>

<!-- SYSTEM CONSOLE SURFACE -->
<p align="center">
  <picture>
    <source media="(prefers-color-scheme: light)" srcset="assets/quantum-terminal-light.svg" />
    <img src="assets/quantum-terminal.svg" width="100%" alt="Active Console Output" />
  </picture>
</p>

---

## ◈ SIGNAL GRID

| Axis | Live Reading |
|----|-------------|
| **Focus** | Local-first orchestration · AI surface hardening |
| **Mode** | Operator > Builder > Designer |
| **Threat Model** | Silent failure, unverifiable automation |
| **Uplink** | [**@Thugger069**](https://github.com/Thugger069) |

---

## ▣ SYSTEM TELEMETRY (GENERATED)

<table width="100%">
<tr>
<td width="50%" align="center" valign="top">
  <h3>Capability Radar</h3>
  <img src="dist/skills-radar.png" alt="Generated Skills Radar" width="100%" />
</td>
<td width="50%" align="center" valign="top">
  <h3>Collaborator Topology</h3>
  <img src="dist/network-graph.png" alt="Network Graph" width="100%" />
</td>
</tr>
</table>

### Technology Adoption Log
<img src="dist/technology-timeline.png" alt="Tech Timeline" width="100%" />

---
"""

    # 2. Dynamic Project Manifest
    manifest_header = "## ⬡ DEPLOYED VESSELS (OPS MANIFEST)\n\n"
    manifest_table_head = "| ID | State | Domain | Description | Stats |\n|----|-------|--------|------------|-------|\n"
    
    rows = []
    for p in projects:
        # Determine status indicator
        status_badges = {
            "SHIP": "`SHIP`",
            "BETA": "`BETA`",
            "ALPHA": "`ALPHA`"
        }
        status = status_badges.get(p.get("status", "DEV"), "`DEV`")
        
        row = f"| **[{p['name']}]({p['link']})** | {status} | {p['domain']} | {p['description']} | ⭐{p['stars']} |"
        rows.append(row)
        
    manifest_section = manifest_header + manifest_table_head + "\n".join(rows) + "\n\n---\n"

    # 3. Footer & Config
    footer = """
## ⚠ OPERATING TENETS (CONFIG)

```yaml
tenets:
  velocity: ship fast without breaking invariants
  integrity: all systems observable and reversible
  infrastructure: local-first, cloud when compounding
  failure_mode: assume drift, design rollback 
<p align="center">
<img src="assets/bg-quantum-grid.svg" width="100%" alt="divider" />
</p>
<div align="center">
<sub>QuantumProfileSurface v3.0 · Automated by Actions</sub>
</div>

# Assemble
final_content = header + manifest_section + footer

with open('README.md', 'w') as f:
    f.write(final_content)

print(">> README.md Generated Successfully.")
if name == "main":
generate_readme()
