#!/usr/bin/env python3
import os
import datetime
import hashlib
from design_engine import (
    gen_hero, 
    gen_thesis, 
    gen_stack, 
    gen_work, 
    gen_telemetry, 
    gen_security
)

def get_pseudo_hash():
    # Deterministic hash based on time window (changes daily)
    today = datetime.datetime.now().strftime("%Y-%m-%d").encode()
    return hashlib.sha256(today).hexdigest()[:8]

def build_readme():
    print("◈ INITIALIZING SPECTRE v5.0 REDESIGN...")
    
    # 1. GENERATE VISUAL ASSETS
    gen_hero()
    gen_thesis()
    gen_stack()
    gen_work()
    gen_telemetry()
    gen_security()
    
    # 2. DEFINE STATIC CONTENT
    ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    build_hash = get_pseudo_hash()
    
    readme_content = f"""<!-- 
    GENERATED BY SPECTRE v5.0 DESIGN ENGINE 
    DO NOT EDIT MANUALLY - EXECUTE scripts/update_readme.py
-->

<div align="center">

<!-- 1. NAVIGATION INDEX -->
<code>
[ THESIS ](#thesis) · [ STACK ](#stack) · [ WORK ](#work) · [ TELEMETRY ](#telemetry) · [ SECURITY ](#security)
</code>

<br /><br />

<!-- 2. HERO / IDENTITY (Dominant Anchor) -->
<a name="hero"></a>
<img src="assets/section_hero.svg" width="1000" alt="IDENTITY_SURFACE" />

<br /><br />

<!-- 3. ENGINEERING THESIS (Quiet / Static) -->
<a name="thesis"></a>
<img src="assets/section_thesis.svg" width="800" alt="ENGINEERING_THESIS" />

<br />

<!-- 4. OPERATIONAL STACK (Structural) -->
<a name="stack"></a>
<img src="assets/section_stack.svg" width="800" alt="OPERATIONAL_STACK" />

<br />

<!-- 5. WORK / DEPLOYMENTS (Flow) -->
<a name="work"></a>
<img src="assets/section_work.svg" width="600" alt="WORK_DEPLOYMENTS" />

<br />

<!-- 6. TELEMETRY (Ambient Monitoring) -->
<a name="telemetry"></a>
<img src="assets/section_telemetry.svg" width="800" alt="LIVE_TELEMETRY" />

<br />

<!-- 7. SECURITY STATUS (Binary Pass/Fail) -->
<a name="security"></a>
<img src="assets/section_security.svg" width="1000" alt="SECURITY_AUDIT" />

<br /><br />

<!-- 8. UPLINK / CONTACT -->
<a name="uplink"></a>
### ◈ UPLINK_ESTABLISHED

| PROTOCOL | ENDPOINT | SLA |
| :--- | :--- | :--- |
| **SMTP** | `popdeuxrem@gateway.net` | `< 24H` |
| **GPG** | `0xSPECTRE_KEY` | `ENCRYPTED_ONLY` |
| **MATRIX** | `@popdeuxrem:matrix.org` | `REALTIME` |

<br />

<!-- 9. FOOTER SIGNATURE (Cryptographic Finality) -->
---
<p align="right">
    <code>BUILD: Surface/v5 · {ts} · SHA256:{build_hash} · invariant</code>
</p>

</div>
"""

    with open('README.md', 'w') as f:
        f.write(readme_content)
    
    print("◈ README.md regeneration complete.")

if __name__ == "__main__":
    build_readme()
