#!/usr/bin/env python3
"""
Evolve README.base.md without destroying the existing v12.0 quantum surface.

This script performs targeted, idempotent edits:
- Preserve existing visual layout and long-form README content.
- Upgrade metadata from v12.0 to v13.0.
- Confirm README.base.md remains canonical.
- Keep AUTO-GENERATED markers intact.
- Let scripts/build_readme.py inject the live surface console.
"""

from __future__ import annotations

import datetime as dt
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README_BASE = ROOT / "README.base.md"

AUTO_START = "<!-- AUTO-GENERATED:START -->"
AUTO_END = "<!-- AUTO-GENERATED:END -->"


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(message)


def main() -> int:
    require(README_BASE.exists(), "README.base.md not found")

    original = README_BASE.read_text(encoding="utf-8")
    content = original

    require(AUTO_START in content, "README.base.md missing AUTO-GENERATED:START")
    require(AUTO_END in content, "README.base.md missing AUTO-GENERATED:END")
    require(content.index(AUTO_START) < content.index(AUTO_END), "README.base.md markers are reversed")

    content = content.replace(
        "POPDEUXREM // QUANTUM SURFACE v12.0",
        "POPDEUXREM // LYSERGIC GITHUB SURFACE ENGINE v13.0",
    )

    content = content.replace(
        "AUTO-GENERATED BY build_readme.py",
        "CANONICAL TEMPLATE + GENERATED BY build_readme.py",
    )

    content = re.sub(
        r"LAST SYNC:\s*[0-9T:\-]+Z\s*\|\s*SHA:\s*[a-fA-F0-9]+",
        "LAST SYNC: 2026-01-01T00:00:00Z | SHA: 0000000000000000",
        content,
        count=1,
    )

    content = content.replace(
        "HERO SURFACE v12.0 // IMMERSIVE ORBITAL IDENTITY",
        "HERO SURFACE v13.0 // IMMERSIVE OPERATIONAL IDENTITY",
    )

    content = content.replace(
        "RUNE-ETCHED NAVIGATION // ANCIENT SCRIPT v12.0",
        "RUNE-ETCHED NAVIGATION // SYSTEM CONTROL INDEX v13.0",
    )

    content = content.replace(
        "CRYSTALLINE JS CORE v12.0 // GEM-FACETED LITERAL STYLE",
        "CRYSTALLINE SYSTEMS CORE v13.0 // GEM-FACETED CONTROL SURFACE",
    )

    content = content.replace(
        "Full+Stack+Engineer;Engineered+Clarity;Tech+Innovator;Open+Source+Enthusiast;Auditable+Systems;Composable+By+Design;Problem+Solver;Quantum+Architect",
        "Systems+Automation+Architect;Deterministic+Infrastructure;Auditable+AI+Systems;Composable+Automation;Production+Grade+Workflows;Observable+Systems;Rollback+Ready+Engineering;Lysergic+Systems+Lab",
    )

    content = content.replace(
        'designation: "PRINCIPAL SYSTEMS ARCHITECT"',
        'designation: "SYSTEMS & AUTOMATION ARCHITECT"',
    )

    content = content.replace(
        'clearance: "QUANTUM_STEALTH"',
        'clearance: "DETERMINISTIC_SURFACE_ENGINE"',
    )

    content = content.replace(
        'primary: "Design systems prioritizing determinism, observability, maintainability"',
        'primary: "Design deterministic, auditable, observable systems that survive production"',
    )

    content = content.replace(
        'focus: "Architecture ∙ Automation ∙ Interface-level control"',
        'focus: "Infrastructure ∙ Automation ∙ Agentic workflows ∙ Interface-level control"',
    )

    content = content.replace(
        'philosophy: "Quantum-grade infrastructure that fails gracefully, scales infinitely"',
        'philosophy: "Production-grade systems: reversible, composable, observable, secure"',
    )

    # Add a static architecture notice immediately before the generated block if absent.
    notice = """<!-- ═══════════════════════════════════════════════════════════════════════════
     LIVE SURFACE CONSOLE // GENERATED OPERATIONAL STATE v13.0
     ═══════════════════════════════════════════════════════════════════════════ -->

<a name="surface"></a>

"""
    if "LIVE SURFACE CONSOLE // GENERATED OPERATIONAL STATE v13.0" not in content:
        content = content.replace(AUTO_START, notice + AUTO_START, 1)

    # Ensure tmp.txt is explicitly deprecated somewhere in the template.
    deprecation = """<!--
ARCHITECTURE NOTE:
README.base.md is the canonical template.
README.md is generated output.
tmp.txt is deprecated and must not be used as a source of truth.
-->
"""
    if "tmp.txt is deprecated and must not be used as a source of truth" not in content:
        content = content.replace("-->\n\n<div align=\"center\">", "-->\n\n" + deprecation + "\n<div align=\"center\">", 1)

    if content != original:
        README_BASE.write_text(content, encoding="utf-8")
        print("UPDATED: README.base.md")
    else:
        print("UNCHANGED: README.base.md")

    print("CHECK: markers intact")
    print("CHECK: canonical template preserved")
    print("CHECK: generated block remains controlled by scripts/build_readme.py")
    print("CHECK: evolved at {}".format(utc_now()))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
